### PR TITLE
Add support for signatures

### PR DESCRIPTION
**Pull request by Vaelatern**

### CODE REVIEW

**Comment by Vaelatern** [comment]
No tests included because I wasn't sure what example object I could use.

**Comment by Vaelatern** [comment]
Seems nose no longer supports python 3.2

**Comment by JasonSanford** [comment]
I think it was requests that wasn't working well with Python 3.2. I don't think that version is supported by the library so I removed support for it here.

**Comment by JasonSanford** [comment]
This has been merged and is available in version 1.4.3

**Pull request merged**
